Rider3:  # Riders Name
  R02: 
    Desc: 'Baseline'
    ValidLaps: [6,7,8,9,10,11]  # TODO correct this! accelerating up to lap ?
  R03: 
    Desc: 'Rod Only'
    ValidLaps: [6,7,8,9,10,11]  # accelerating up to lap 6
  R04:  
    Desc: '50mm Disc'
    ValidLaps: [5,6,7,8,9,10,11]  # accelerating up to lap 5
  R05:  
    Desc: '60mm Disc'
    ValidLaps: [6,7,8,9,10,11]  # accelerating up to lap 6
  R06:  
    Desc: 'Baseline 2'
    ValidLaps: [5,6,7,8,9,10,11]  # accelerating up to lap 5
  R07:  
    Desc: '80mm Disc'
    ValidLaps: [4,5,6,7,8,9,10,11]  # accelerating up to lap 4
  R08:  
    Desc: '100mm Disc'
    ValidLaps: [5,6,7,8,9,10,11]  # accelerating up to lap 5
  R09:  
    Desc: 'Baseline 3'
    ValidLaps: [3,4,5,6,7,8,9,10,11]
  R10:  
    Desc: 'Shuffle'
    ValidLaps: [3,4,5,6,7,8,9,10,11,12,13]
    Sprocket: 13


