# Rider Settings (Lance.C)
RIDER_WEIGHT: 65.5

# Bike settings
BIKE_WEIGHT: 11.1     # BMC bike without rod+discs
ROD_DISC_WEIGHT: 0.25 # Rod with 2x T-Clamp = 183.1g, 100mm discs with T-Clamp = 60.5g (Total 244g)  40mm discs with T-Clamp = 38.5g

CRR: 0.0025           # check what BR have set this to for their data processing
BIKE_DTL: 4.0         # % loss to drive train 
AH_CF: 1.22           # Aerohead Rider Compensation Factor or Correction Factor

# Wheel settings usually refer to the front wheel where the speed sensor is positioned 
WHEEL_CIRC_ACTUAL: 2106 # 1mm more than setting for rider 2 on same bike (Lance is 15kg lighter) 
WHEEL_CIRC_BR_SETTING: 2096  # matched odo speed to ground speed
REAR_WHEEL_CIRC: 2107   # 2107 matcheds crank speed to ground speed when front wheel at 2106  (2097 rear matches 2096 front)                  
CHAINRING: 50.0         # Best fit to data 
SPROCKET: 14            # Best fit to all test runs except last

# Height settings
COM_HEIGHT: 1.1         # using saddle height for Centre of Mass for both rider and bike (saddle ranges 1.02 to 1.05)
COM_RIDER_HEIGHT: 1.2   # higher than COM_HEIGHT as bike mass is excluded so all weight in body and legs. 
COP_HEIGHT: 1.2         # Centre of Pressure (centre of Frontal Area) - will be slightly higher than CoM as FA of bike is much smaller for its mass (displaced more lengthwise)
COP_RIDER_HEIGHT: 1.25  # keeping this close to COP_HEIGHT because FA of bike is small and addition of rod and discs lower than saddle will offset this 
PITOT_HEIGHT: 0.76      # Height of Pitot tube where air speed is measured

TEMP_SENSOR_RHO: Temp_C # temp sensor field used for calculating Air Density e.g. temp103T (HB Inclinometer) instead of Temp_C from Aerohead